{% set name = "latexindent.pl" %}
{% set version = "3.23.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cmhughes/{{ name }}/archive/V{{ version }}.tar.gz
  sha256: e6df687a4ddc161e2004ac778828e3e5e013fa87d52bb74c5080b822902c1dad

build:
  number: 0
  noarch: generic
  script:
    - perl Makefile.PL INSTALLDIRS=vendor NO_PERLLOCAL=1 NO_PACKLIST=1
    - make
    - make test
    - make install VERBINST=1

requirements:
  build:
    - make
  host:
    - perl
  run:
    - perl
    - perl-file-homedir
    - perl-yaml-tiny

test:
  commands:
    - {{ name }} --version | grep {{ version }}

about:
  home: https://github.com/cmhughes/{{ name }}
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: Script to indent LaTeX code

extra:
  recipe-maintainers:
    - tdegeus
