{% set name = "latexindent.pl" %}
{% set version = "3.13.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cmhughes/{{ name }}/archive/V{{ version }}.tar.gz
  sha256: cc6df51754f2bed022eaaecb00576162c9a1127c6ca7beb67218ac9278aff132

build:
  number: 0
  noarch: generic
  script:
    - cp {{ name }} $PREFIX/bin/
    - cp -r LatexIndent $PREFIX/bin/
    - cp defaultSettings.yaml $PREFIX/bin/LatexIndent/

requirements:
  build:
    - make
  host:
    - perl
  run:
    - perl
    - perl-file-homedir
    - perl-unicode-linebreak
    - perl-yaml-tiny

test:
  commands:
    - {{ name }} --version

about:
  home: https://github.com/cmhughes/{{ name }}
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: Script to indent LaTeX code

extra:
  recipe-maintainers:
    - tdegeus
