{% set name = "latexindent.pl" %}
{% set version = "3.24.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cmhughes/{{ name }}/archive/V{{ version }}.tar.gz
  sha256: 7b7216604d1e544b7f22cf520b3ca1817222e70e28fe2865bcc4d0e3284c497c

build:
  number: 0
  noarch: generic
  script:
    - perl Makefile.PL INSTALLDIRS=vendor NO_PERLLOCAL=1 NO_PACKLIST=1
    - make
    - make test
    - make install VERBINST=1

requirements:
  build:
    - make
  host:
    - perl
  run:
    - perl
    - perl-file-homedir
    - perl-yaml-tiny

test:
  commands:
    - {{ name }} --version | grep {{ version }}

about:
  home: https://github.com/cmhughes/{{ name }}
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: Script to indent LaTeX code

extra:
  recipe-maintainers:
    - tdegeus
