{% set name = "latexindent.pl" %}
{% set version = "3.23.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cmhughes/{{ name }}/archive/V{{ version }}.tar.gz
  sha256: 0373bd173a23af1e4aa3685086c3cd44836911249bc53234d9b3aea5807c4559

build:
  number: 0
  noarch: generic
  script:
    - perl Makefile.PL INSTALLDIRS=vendor NO_PERLLOCAL=1 NO_PACKLIST=1
    - make
    - make test
    - make install VERBINST=1

requirements:
  build:
    - make
  host:
    - perl
  run:
    - perl
    - perl-file-homedir
    - perl-yaml-tiny

test:
  commands:
    - {{ name }} --version | grep {{ version }}

about:
  home: https://github.com/cmhughes/{{ name }}
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE.txt
  summary: Script to indent LaTeX code

extra:
  recipe-maintainers:
    - tdegeus
